[build]
  command = "EXPO_NO_EXPORT_EMBEDDED_ASSETS=1 npx expo export -p web --no-bytecode --clear"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "expo"
  targetPort = 19006

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
